import uuid
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, Text, func
from sqlalchemy.orm import relationship
from app.database import Base
class QRToken(Base):
    """
    SQLAlchemy model representing dynamic QR codes generated by the system.
    Tracks expiration, usage, and linkage to specific examinations for verification.
    """
    __tablename__ = "qr_tokens"
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    exam_id = Column(String(36), ForeignKey("exams.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False)
    token_type = Column(String(50), nullable=False, default="START_EXAM") # 'START_EXAM', 'VERIFICATION'
    token_value = Column(Text, nullable=False) # Stores signature payload or encrypted key values
    is_used = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, server_default=func.now())
    expires_at = Column(DateTime, nullable=False)
    # Relationships
    exam = relationship("Exam", back_populates="qr_tokens")
    def __repr__(self) -> str:
        return f"<QRToken exam_id={self.exam_id} type={self.token_type} used={self.is_used}>"
