CREATE DATABASE IF NOT EXISTS qr_exam_system;
USE qr_exam_system;
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------
-- Table: users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    role ENUM('student', 'invigilator', 'admin') NOT NULL DEFAULT 'student',
    public_key TEXT NULL, -- PEM-encoded RSA-2048 public key generated by student's device
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_users_username (username),
    UNIQUE INDEX idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: subjects
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS subjects (
    id VARCHAR(36) NOT NULL,
    code VARCHAR(20) NOT NULL, -- e.g., 'CS-101'
    name VARCHAR(100) NOT NULL, -- e.g., 'Introduction to Computer Science'
    description TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX idx_subjects_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: exams
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS exams (
    id VARCHAR(36) NOT NULL,
    subject_id VARCHAR(36) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    duration_minutes INT NOT NULL,
    encrypted_questions LONGBLOB NOT NULL, -- AES-256-GCM encrypted JSON payload of questions
    passcode_hash VARCHAR(255) NOT NULL, -- Verification code for Invigilator to unlock manually
    status ENUM('draft', 'scheduled', 'ongoing', 'completed') NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_exams_subjects
        FOREIGN KEY (subject_id)
        REFERENCES subjects (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    INDEX idx_exams_start_time (start_time),
    INDEX idx_exams_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: student_exams
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_exams (
    id VARCHAR(36) NOT NULL,
    student_id VARCHAR(36) NOT NULL,
    exam_id VARCHAR(36) NOT NULL,
    status ENUM('registered', 'started', 'submitted', 'flagged', 'absent') NOT NULL DEFAULT 'registered',
    encrypted_answers LONGBLOB NULL, -- Answers payload encrypted with Server RSA Public key
    client_signature TEXT NULL, -- Digital signature generated with Student Device Private key
    started_at DATETIME NULL,
    submitted_at DATETIME NULL,
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX uq_student_exam (student_id, exam_id),
    CONSTRAINT fk_student_exams_users
        FOREIGN KEY (student_id)
        REFERENCES users (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_student_exams_exams
        FOREIGN KEY (exam_id)
        REFERENCES exams (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: violations
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS violations (
    id VARCHAR(36) NOT NULL,
    student_exam_id VARCHAR(36) NOT NULL,
    violation_type ENUM('SCREENSHOT', 'APP_BACKGROUNDED', 'INTERNET_ON', 'CLOCK_DRIFT', 'USB_CONNECTED') NOT NULL,
    timestamp DATETIME NOT NULL,
    details TEXT NULL,
    chain_index INT NOT NULL, -- Sequential block number in client tamper-evident log (0, 1, 2...)
    hash_value VARCHAR(64) NOT NULL, -- SHA-256 hash verifying integrity up to this entry
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_violations_student_exams
        FOREIGN KEY (student_exam_id)
        REFERENCES student_exams (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    INDEX idx_violations_type (violation_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE invigilator_credentials
(
 id VARCHAR(36),
 username VARCHAR(50),
 password_hash VARCHAR(255),
 exam_id VARCHAR(36),
 expires_at DATETIME
);
CREATE TABLE qr_tokens
(
 id VARCHAR(36),
 exam_id VARCHAR(36),
 token VARCHAR(255),
 expires_at DATETIME
);
-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;